# 工作流名称
name: Deploy VitePress site to Pages

# 触发条件：当 main 分支有更新时运行
on:
  push:
    branches: [main]

# 允许 GITHUB_TOKEN 拥有写入 Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在跑
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整 git 历史，这对 VitePress 的 lastUpdated 功能很重要

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci # 使用 ci 比 install 更快更稳定

      - name: Build with VitePress
        run: |
          npm run docs:build # 执行你在 package.json 里定义的构建命令
          touch docs/.vitepress/dist/.nojekyll # 告诉 GitHub 不要忽略下划线开头的文件

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # 👈 关键：指定构建产物的路径

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
